//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysadminsLV.PKI.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysadminsLV.PKI.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIMnzCCC4cCAQEwDQYJKoZIhvcNAQELBQAwdTELMAkGA1UEBhMCVVMxFTATBgNV
        ///BAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTE0MDIG
        ///A1UEAxMrRGlnaUNlcnQgU0hBMiBFeHRlbmRlZCBWYWxpZGF0aW9uIFNlcnZlciBD
        ///QRcNMTQwNTAzMTcwMTE1WhcNMTQwNTEwMTcwMDAwWjCCCqowIQIQCM+Fzj8sIXzo
        ///AAz+W4lByhcNMTMxMTIzMTUyOTAzWjAhAhAOChOgljbSbDcxl6CYI3wBFw0xMzEx
        ///MjMxNTI5MDNaMCECEAZ2/6z0P6xowjDywFWH6+MXDTEzMTEyMzE1MjkwM1owIQIQ
        ///DGEgHMK/CykeSiLkV3+6QhcNMTMxMTIzMTUyOTAzWjAhAhAL4CedA/cCICIdyTsU
        ///Uh6AFw0xMzEyMTMwMzE5MDJaMCECEAwz1ZZIy7Vrvjm1xB5EAf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseCRLSHA256v2 {
            get {
                return ResourceManager.GetString("BaseCRLSHA256v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIMDDNowgwMLwTANBgkqhkiG9w0BAQUFADCBvjELMAkGA1UEBhMCVVMxFzAVBgNV
        ///BAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQLExZWZXJpU2lnbiBUcnVzdCBOZXR3
        ///b3JrMTswOQYDVQQLEzJUZXJtcyBvZiB1c2UgYXQgaHR0cHM6Ly93d3cudmVyaXNp
        ///Z24uY29tL3JwYSAoYykwNjE4MDYGA1UEAxMvVmVyaVNpZ24gQ2xhc3MgMyBFeHRl
        ///bmRlZCBWYWxpZGF0aW9uIFNTTCBTR0MgQ0EXDTE0MDUwNDA5MDAxMVoXDTE0MDUx
        ///MTA5MDAxMVowgwMKzjAhAhABEnUGiTsT/4hHy6U47d1bFw0xMzA1MDExNzE4NTJa
        ///MCECEAETwjmrf0t/SEJepfc3e68XDTEzMTIyNzAxMDMyNFowIQIQARPa//6DLRmd
        ///ZIRfVcym5BcNMTMwNTIxMDkyNDIwWjAhAhABFNFBjOUfoA86yI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseCRLv1 {
            get {
                return ResourceManager.GetString("BaseCRLv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIC1DCCAbwCAQEwDQYJKoZIhvcNAQEFBQAwajELMAkGA1UEBhMCTFYxFDASBgNV
        ///BAoTC0FkYXR1bSBMdGQuMRwwGgYDVQQLExNJbmZvcm1hdGlvbiBTeXN0ZW1zMScw
        ///JQYDVQQDEx5BZGF0dW0gQ2xhc3MgMSBJc3N1aW5nIFN1YkNBIDEXDTEwMDQxMzEx
        ///MTE0NFoXDTEwMDQxOTExMzE0NFowVzAbAgpheMkkAAAAAAAIFw0xMDA0MTIxNjM0
        ///MDBaMBsCCmERD08AAAAAAAQXDTEwMDQwMzEzMTEwMFowGwIKYQzBIwAAAAAAAxcN
        ///MTAwNDAzMTExNzAwWqCBxDCBwTAfBgNVHSMEGDAWgBTrI1ah3EJJATIBKNKS3Qnk
        ///zLwB1TAQBgkrBgEEAYI3FQEEAwIBADAKBgNVHRQEAwIBHDAcBgkrBgEEAYI3FQQE
        ///DxcNMTAwNDE4MTEyMTQ0WjBiBgNVHS4EWzBZMFegVaBThipodH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseCRLv2 {
            get {
                return ResourceManager.GetString("BaseCRLv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIICozCCAikCAQAwgcExCzAJBgNVBAYTAkxWMRMwEQYDVQQIEwpSaWdhcyByYWou
        ///MRAwDgYDVQQHEwdKdXJtYWxhMRUwEwYDVQQKEwxTeXNhZG1pbnMgTFYxHjAcBgNV
        ///BAsTFURpdmlzaW9uIG9mIElUIChEb0lUKTEcMBoGA1UECxMTSW5mb3JtYXRpb24g
        ///U3lzdGVtczE2MDQGA1UEAxMtU3lzYWRtaW5zIExWIENsYXNzIDEgRXh0ZW5kZWQg
        ///VmFsaWRhdGlvbiBDQS0yMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEmYRvn2B81yDq
        ///HWJmcZ8h1UL1HafRmTp0s2PzQ7kCJ+6NDxodq4JiXVXSTYg6b2qBaTBbT9rmXF1M
        ///CDMgTWYyCta7LTUj2viDL+PmMBeajIeLrY4niFWuBc0b6pPjNbc2oIHnMBsGCisG
        ///AQQBgjcNAgMxDRYLNi4zLjk2MDAuMi4wgccGCSqGSIb3DQEJDj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CNGReq {
            get {
                return ResourceManager.GetString("CNGReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIEpzCCA4+gAwIBAgIKYZ1g8AAAAAAAAjANBgkqhkiG9w0BAQUFADB+MQswCQYD
        ///VQQGEwJMVjEVMBMGA1UEChMMU3lzYWRtaW5zIExWMRwwGgYDVQQLExNJbmZvcm1h
        ///dGlvbiBTeXN0ZW1zMTowOAYDVQQDEzFTeXNhZG1pbnMgTFYgQ2xhc3MgMSBSb290
        ///IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTEwMDQxNDE3NDExNloXDTIwMDQx
        ///NDE2MjU1NVowcjELMAkGA1UEBhMCTFYxFTATBgNVBAoTDFN5c2FkbWlucyBMVjEc
        ///MBoGA1UECxMTSW5mb3JtYXRpb24gU3lzdGVtczEuMCwGA1UEAxMlU3lzYWRtaW5z
        ///IExWIEludGVybmFsIENsYXNzIDEgU3ViQ0EtMTCCASIwDQYJKoZIhvcNAQEBBQAD
        ///ggEPADCCAQoCggEBALhx8OUm5GGYqdGXi4dryi10+lORR8CmQ1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRLIssuer {
            get {
                return ResourceManager.GetString("CRLIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIICYDCCAUgCAQEwDQYJKoZIhvcNAQEFBQAwajELMAkGA1UEBhMCTFYxFDASBgNV
        ///BAoTC0FkYXR1bSBMdGQuMRwwGgYDVQQLExNJbmZvcm1hdGlvbiBTeXN0ZW1zMScw
        ///JQYDVQQDEx5BZGF0dW0gQ2xhc3MgMSBJc3N1aW5nIFN1YkNBIDEXDTEwMDQxMzE2
        ///MTQxNloXDTEwMDQxNDE2MzQxNlowOjAbAgo0ppGsAAAAAAAKFw0xMDA0MTMxNjI0
        ///MDBaMBsCCmF4ySQAAAAAAAgXDTEwMDQxMjE2MzQwMFqgbjBsMB8GA1UdIwQYMBaA
        ///FOsjVqHcQkkBMgEo0pLdCeTMvAHVMBAGCSsGAQQBgjcVAQQDAgEAMAoGA1UdFAQD
        ///AgEdMBwGCSsGAQQBgjcVBAQPFw0xMDA0MTQwNDI0MTZaMA0GA1UdGwEB/wQDAgES
        ///MA0GCSqGSIb3DQEBBQUAA4IBAQCDWeO85whlLNecxNHSM2kjtP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeltaCRLv2 {
            get {
                return ResourceManager.GetString("DeltaCRLv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCygKqAohiZodHRwOi8vd3d3LnN5c2FkbWlucy5sdi9wa2kvZXZjYS0yLmNybA==.
        /// </summary>
        internal static string Extension_IDP {
            get {
                return ResourceManager.GetString("Extension_IDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIBSDCBzgIBATAKBggqhkjOPQQDAzCBrTELMAkGA1UEBhMCTFYxEzARBgNVBAgT
        ///ClJpZ2FzIHJhai4xEDAOBgNVBAcTB0p1cm1hbGExFTATBgNVBAoTDFN5c2FkbWlu
        ///cyBMVjEeMBwGA1UECxMVRGl2aXNpb24gb2YgSVQgKERvSVQpMUAwPgYDVQQDEzdT
        ///eXNhZG1pbnMgTFYgQ2xhc3MgMSBTSEEtMiBSb290IENlcnRpZmljYXRpb24gQXV0
        ///aG9yaXR5Fw0xNTAyMjMxODE3MThaMAoGCCqGSM49BAMDA2kAMGYCMQDexFxhNtyU
        ///TUWqPiejAT3XqWkBgjhXM9uKbtp6HrFkbFiI/sov2b+aD0//ifXBcPsCMQC5v9vT
        ///rxP0Sx/xWH6QUVbgNOgSE+lwhUkwH39T8EE+JHkPN+Iho0rIU0NrXTDhIw4=.
        /// </summary>
        internal static string MinimalCRL {
            get {
                return ResourceManager.GetString("MinimalCRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIOkzCCDHugAwIBAgISESDgC3GwzGwNav7yUnQF/iAGMA0GCSqGSIb3DQEBCwUA
        ///MGExCzAJBgNVBAYTAkRFMTYwNAYDVQQKDC1FdXJvcGVhbiBBZXJvbmF1dGljIERl
        ///ZmVuY2UgYW5kIFNwYWNlIENvbXBhbnkxGjAYBgNVBAMMEUVBRFMgUzIgUm9vdCBD
        ///QSAxMB4XDTEzMDcxMTAwMDAwMFoXDTI2MDcxMTAwMDAwMFowXzELMAkGA1UEBhMC
        ///REUxNjA0BgNVBAoMLUV1cm9wZWFuIEFlcm9uYXV0aWMgRGVmZW5jZSBhbmQgU3Bh
        ///Y2UgQ29tcGFueTEYMBYGA1UEAwwPRUFEUyBlY29TSEEyQ0ExMIICIjANBgkqhkiG
        ///9w0BAQEFAAOCAg8AMIICCgKCAgEA1Ekf0rrqbMmwcQ5biTIs6mq3jcmBGYSkSK34
        ///cd/TqNSKvE7q7m/LICrPMNBniwspbOc2MmuobEwP4R06noPPsZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultiCDP {
            get {
                return ResourceManager.GetString("MultiCDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIG9MIGYMAkGBSsOAwIaBQAwRzETMBEGCgmSJomT8ixkARkWA2NvbTEXMBUGCgmS
        ///JomT8ixkARkWB2NvbnRvc28xFzAVBgNVBAMTDmNvbnRvc28tREMyLUNBFw0xMDAz
        ///MDYxMTEwMzFaFw0xNTAzMDUxMTEwMzFaMCQwIgIDEjRWFw0xMjA3MjQxNDI3MDVa
        ///MAwwCgYDVR0VBAMKAQMwCQYFKw4DAhoFAAMVAA4N+FY48JTRcNkFdE8EXRKH3/Pf.
        /// </summary>
        internal static string NoSignCRL {
            get {
                return ResourceManager.GetString("NoSignCRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIKEgIBAzCCCc4GCSqGSIb3DQEHAaCCCb8Eggm7MIIJtzCCBgAGCSqGSIb3DQEHAaCCBfEEggXtMIIF6TCCBeUGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAgIeYq026FzfgICB9AEggTY0AOAB/5cFSWYdMR9XlC0qCR2ce/ppKf041LO1722jFJ9F+sLepKPN+p6P0KtSjNHWOt7WoJuyyT8sqVUuKKWZWsRNXWxzLFpDYdyEQJoRgqC/9i3j4eDd68HNy1UaKwWDa2AOHXfPET29eMn4ms5WdePoG0QsHzRFs+f1l2Y+SZ14ZLru2ab2bFHP4vxsTL9hiHSTygcQ+uA5eIUnGvrTaB5tJJZhiJli2NPHMRpqiCCE7n608dhvKk4T4zNNpGq920ni4ljjIsyVTJydU1XCmiZnZ4wLQg9J80ZzQfIsl/lAKa8ynop8sYzhC7Nb2lWfRw/xsScteVLkuV1Hs7PSBigza5oknBE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PFX_CTLSIGN_PWD_1 {
            get {
                return ResourceManager.GetString("PFX_CTLSIGN_PWD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIXcAYJKoZIhvcNAQcCoIIXYTCCF10CAQExCzAJBgUrDgMCGgUAMGgGCisGAQQBgjcCAQSgWjBYMDMGCisGAQQBgjcCAQ8wJQMBAKAgoh6AHAA8ADwAPABPAGIAcwBvAGwAZQB0AGUAPgA+AD4wITAJBgUrDgMCGgUABBSn9L6kpyMVm6VVAUSNEbe4rZOgnaCCEvUwggOfMIICh6ADAgECAhB5oqWF+dEVQhPZuD72to3tMA0GCSqGSIb3DQEBBQUAMFMxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5WZXJpU2lnbiwgSW5jLjErMCkGA1UEAxMiVmVyaVNpZ24gVGltZSBTdGFtcGluZyBTZXJ2aWNlcyBDQTAeFw0xMjA1MDEwMDAwMDBaFw0xMjEyMzEyMzU5NTlaMGIxCzAJBgNVBAYTAlVTMR0wGwYDVQQKExRTeW1hbnRlYyBDb3Jwb3JhdGlvbjE0MDIGA1UEAxMrU3ltYW50ZWMgVGltZSBT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PKCS_TimeAuthSignExpired {
            get {
                return ResourceManager.GetString("PKCS_TimeAuthSignExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIEFjCCAv4CAQAwLjEsMCoGA1UEAwwjWFgtVU5JVC1FWEFNUExFLndvcmtzdGF0
        ///aW9uLm9mZmxpbmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDpaKsr
        ///A4xlUWZoQ5+FVnPailOV4nao5Jbe4UyNiCaE1qyA/C4ymaMQY6KYbhCA+hms/fgT
        ///CNHfll2I+qiZMbADDgZgeKwZrLFmQSPUgyRSC+JiAFq+cL0lLB8ZFJDSHJIsPQRO
        ///0Jy5h2TEZMAjVIMR67Nx5ZEyUWbIzJR8NC6gYNuE4DbBJo1Rb4j2Uyag5YPlWyzK
        ///06P7YH4x2/doazp9KD/bXpi0QCTRKrzyL9ZzNkvJGGWUbeF98qAGI6DHWqem7NT4
        ///F/wZoudYFgNvTFEXP0J2rvjLibH7rxI9+DE1ie8o3lq0XrySfSBT+IcaOVtdZnDE
        ///i575WOhlLlSkqAijAgMBAAGgggGhMBoGCisGAQQBgjcNAgMxDB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pkcs10req {
            get {
                return ResourceManager.GetString("pkcs10req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIbEwYJKoZIhvcNAQcCoIIbBDCCGwACAQExDzANBglghkgBZQMEAgEFADCCBmMG
        ///CSqGSIb3DQEHAaCCBlQEggZQMIIGTAYJKoZIhvcNAQcDoIIGPTCCBjkCAQAxggFx
        ///MIIBbQIBADBVMEcxEzARBgoJkiaJk/IsZAEZFgNjb20xFzAVBgoJkiaJk/IsZAEZ
        ///Fgdjb250b3NvMRcwFQYDVQQDEw5jb250b3NvLURDMi1DQQIKFS0SnQACAAABxzAN
        ///BgkqhkiG9w0BAQEFAASCAQAw5mLIewXJQbMEirinpca5ZC5kNhFfWDSfl8sLmpqP
        ///BYR0XLKD9418a4Bt5F/jz2bGmggUVlrSkxCJ0+58ItdtBlL7Hl5u3hi+ODVUdkIP
        ///7tv3L/pa212QR9GtB6Ph23jRsXn9O02mN62ZrI761r9nTh2NtOQsalKEb+cDCbaR
        ///Jk4abDnESxZ/LyV/dvCuDxHn9imcR60aR8fYF25jh9mZr6JqVE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pkcs7generic {
            get {
                return ResourceManager.GetString("pkcs7generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIGhAYJKoZIhvcNAQcCoIIGdTCCBnECAQMxCzAJBgUrDgMCGgUAMIIE3gYIKwYB
        ///BQUHDAKgggTQBIIEzDCCBMgwbTBrAgECBgorBgEEAYI3CgoBMVowWAIBADADAgEB
        ///MU4wTAYJKwYBBAGCNxUUMT8wPQIBBQwdSVUtTVNTRy1GUkVEODEudGVzdGFkcy5p
        ///dS5lZHUMEFRFU1RBRFNcdHNrZnNlcnYMB01NQy5FWEUwggRRoIIETQIBATCCBEYw
        ///ggMuAgEAMDcxHDAaBgNVBAMME0Fub3RoZXIgQ29tbW9uIE5hbWUxFzAVBgNVBAMM
        ///DnRoaXMgaXMgYSB0ZXN0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
        ///mII5rwfdmVj9NReG7lOgaR+QakHU6h58b/zHclOe19t+37+bncK4LTokhzvO/6gk
        ///Bd3J2XylHUlYVEwSXq28Lq05ZRSz70pE/qbUP/hbP/h/JJr2gD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pkcs7req {
            get {
                return ResourceManager.GetString("pkcs7req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIHUpDUwMzETMBEGCgmSJomT8ixkARkWA2NvbTENMAsGA1UECwwEdGVzdDENMAsGA1UEAwwEbWFp
        ///boIPd3d3LmNvbnRvc28uY29tgRFlbWFpbEBjb21wYW55LmNvbYcEwKgCOIcQIAENuIWjCNMTGYou
        ///A3BzSIgJKwYBBAGCNxkBhhVodHRwczovL3ZlcmlzaWduLmNvbS+gIQYKKwYBBAGCNxQCA6ATDBFh
        ///ZG1pbkBjb250b3NvLmNvbaAaBgQrOActoBIEEM9Hl/S980x3jgURhMIb+3k=.
        /// </summary>
        internal static string SAN {
            get {
                return ResourceManager.GetString("SAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MHIxCzAJBgNVBAYTAkxWMRUwEwYDVQQKEwxTeXNhZG1pbnMgTFYxHDAaBgNVBAsTE0luZm9ybWF0aW9uIFN5c3RlbXMxLjAsBgNVBAMTJVN5c2FkbWlucyBMViBJbnRlcm5hbCBDbGFzcyAxIFN1YkNBLTE=.
        /// </summary>
        internal static string X500Name {
            get {
                return ResourceManager.GetString("X500Name", resourceCulture);
            }
        }
    }
}
