//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysadminsLV.PKI.Tests.Cryptography.X509Certificates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Certificates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Certificates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysadminsLV.PKI.Tests.Cryptography.X509Certificates.Certificates", typeof(Certificates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIEyTCCA7GgAwIBAgIOZZuzFzUlDwgAAgAABYUwDQYJKoZIhvcNAQEFBQAwRzET
        ///MBEGCgmSJomT8ixkARkWA2NvbTEXMBUGCgmSJomT8ixkARkWB2NvbnRvc28xFzAV
        ///BgNVBAMTDmNvbnRvc28tREMyLUNBMB4XDTEyMDQyMjA5MDQ0MFoXDTEzMDQyMjA5
        ///MDQ0MFowVjETMBEGCgmSJomT8ixkARkWA2NvbTEXMBUGCgmSJomT8ixkARkWB2Nv
        ///bnRvc28xDjAMBgNVBAMTBVVzZXJzMRYwFAYDVQQDEw1BZG1pbmlzdHJhdG9yMFkw
        ///EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEjMKOpXzykyn7wOFEOH9798FGv31GjkH
        ///0EWpMBXwOn95D8xjo7ZTFEdjPleyFr2jb+BdsGNbaGRpsDuaS9lYY6OCAm0wggJp
        ///MDwGCSsGAQQBgjcVBwQvMC0GJSsGAQQBgjcVCImQBoO+uDuHwY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cert_ECC {
            get {
                return ResourceManager.GetString("Cert_ECC", resourceCulture);
            }
        }
    }
}
