//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysadminsLV.PKI.Tests.Cryptography.X509Certificates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Extensions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Extensions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysadminsLV.PKI.Tests.Cryptography.X509Certificates.Extensions", typeof(Extensions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFGhS6RJMEcxCzAJBgNVBAYTAkhLMRYwFAYDVQQKEw1Ib25na29uZyBQb3N0MSAwHgYDVQQDExdIb25na29uZyBQb3N0IFJvb3QgQ0EgMYICA+g=.
        /// </summary>
        internal static string AKIIssuerSerial {
            get {
                return ResourceManager.GetString("AKIIssuerSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBaAFJ39/KrFuybixJrV0EtdamEKirpD.
        /// </summary>
        internal static string AkiKeyId {
            get {
                return ResourceManager.GetString("AkiKeyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAaAAQaBAQo=.
        /// </summary>
        internal static string AppPolicyConstraintsFull {
            get {
                return ResourceManager.GetString("AppPolicyConstraintsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAOBAQo=.
        /// </summary>
        internal static string AppPolicyConstraintsInhibit {
            get {
                return ResourceManager.GetString("AppPolicyConstraintsInhibit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAOAAQY=.
        /// </summary>
        internal static string AppPolicyConstratinsRequired {
            get {
                return ResourceManager.GetString("AppPolicyConstratinsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCYwEQYJKwYBBAGCNxVABgQqAwRiMBEGCSsGAQQBgjcVQQYEKgMEZA==.
        /// </summary>
        internal static string AppPolicyMappings {
            get {
                return ResourceManager.GetString("AppPolicyMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAaAAQOBAQU=.
        /// </summary>
        internal static string CertPolicyConstraintsFull {
            get {
                return ResourceManager.GetString("CertPolicyConstraintsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAOBAQU=.
        /// </summary>
        internal static string CertPolicyConstraintsInhibit {
            get {
                return ResourceManager.GetString("CertPolicyConstraintsInhibit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAOAAQM=.
        /// </summary>
        internal static string CertPolicyConstraintsRequired {
            get {
                return ResourceManager.GetString("CertPolicyConstraintsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCYwEQYJKwYBBAGCNxU1BgQqAwRXMBEGCSsGAQQBgjcVNgYEKgMEWQ==.
        /// </summary>
        internal static string CertPolicyMappings {
            get {
                return ResourceManager.GetString("CertPolicyMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFICARgwTTBLhhNodHRwOi8vJTEvUHVibGljL015hh1mdHA6Ly9mb28uY29tL1B1YmxpYy9NeUNBLmNydIYVZmlsZTovL1xcJTFcUHVibGljXE15.
        /// </summary>
        internal static string CrossCertDistrPoint {
            get {
                return ResourceManager.GetString("CrossCertDistrPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIB1aCCAVswLKAqBgorBgEEAYI3FAIDoBwMGmFkbWluaXN0cmF0b3JAc3lzYWRtaW5zLmx2MA+BDUBzeXNhZG1pbnMubHYwDoIMLmNvbnRvc28uY29tMDOkMTAvMRIwEAYKCZImiZPyLGQBGRYCTFYxGTAXBgoJkiaJk/IsZAEZFglzeXNhZG1pbnMwD4YNLnN5c2FkbWlucy5sdjAohiZodHRwczovL2xvY2FsaG9zdC9jZXJ0c3J2L2RlZmF1bHQuaHRtbDAihiBcXGxvY2FsaG9zdFxjZXJ0c3J2XGRlZmF1bHQuaHRtbDAKhwgKAQCs///4ADAihyAAAAAAAAAAAAAAAAD//xKs////////AAAAAAAAAAAAADAihyASNFZ4mrze8DIQdlS6mP7c//////+AAAAAAAAAAAAAADAihyASNAAAAADe8DIQdlS6mP7c/////////////////////6F0MB6gHAYKKwYBBAGCNxQCA6AODAxAY29udG9z [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NameConstraints {
            get {
                return ResourceManager.GetString("NameConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDigNjASoBAGCisGAQQBgjcUAgOgAgwAMAKBADAOggxzeXNhZG1pbnMubHYwBKQCMAAwAoYAMAKHAA==.
        /// </summary>
        internal static string NameConstraintsEmpty {
            get {
                return ResourceManager.GetString("NameConstraintsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIHTpDUwMzETMBEGCgmSJomT8ixkARkWA2NvbTENMAsGA1UECwwEdGVzdDENMAsGA1UEAwwEbWFpboIPd3d3LmNvbnRvc28uY29tgRFlbWFpbEBjb21wYW55LmNvbYcEwKgCOIcQIAENuIWjCNMTGYouA3BzSIgJKwYBBAGCNxkBhhRodHRwczovL3ZlcmlzaWduLmNvbaAhBgorBgEEAYI3FAIDoBMMEWFkbWluQGNvbnRvc28uY29toBoGBCs4By2gEgQQz0eX9L3zTHeOBRGEwhv7eQ==.
        /// </summary>
        internal static string SAN {
            get {
                return ResourceManager.GetString("SAN", resourceCulture);
            }
        }
    }
}
