//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysadminsLV.PKI.Tests.Cryptography.X509Certificates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SignerData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignerData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysadminsLV.PKI.Tests.Cryptography.X509Certificates.SignerData", typeof(SignerData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIBsTCCAUoCAQAwADBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKe1+FeCIEU5
        ///S9Wf0xPq0mx9xys191QoVrcbFjPDByZN3u0i58VTM3Aqdv4YHVqDZ5BhYQSLmglo
        ///Nxq7ydMXmo6ggecwHAYKKwYBBAGCNw0CAzEOFgwxMC4wLjE2Mjk5LjIwLgYJKoZI
        ///hvcNAQkOMSEwHzAdBgNVHQ4EFgQUKOtYq5wamhsandDEUSrJEuxsEZIwLwYJKwYB
        ///BAGCNxUUMSIwIAIBBQwEVGhvcgwMVEhPUlx2UG9kYW5zDAdNTUMuRVhFMGYGCisG
        ///AQQBgjcNAgIxWDBWAgEAHk4ATQBpAGMAcgBvAHMAbwBmAHQAIABTAG8AZgB0AHcA
        ///YQByAGUAIABLAGUAeQAgAFMAdABvAHIAYQBnAGUAIABQAHIAbwB2AGkAZABlAHID
        ///AQAwGAYHKoZIzj0EAzANBglghkgBZQMEAgIFAANHADBEAiBvSu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ECDSAP256SHA384SPECIFIED {
            get {
                return ResourceManager.GetString("ECDSAP256SHA384SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIDBjCCAsUCAQAwADCCAbcwggErBgcqhkjOOAQBMIIBHgKBgQCjzhigqpFCwcRW
        ///pw8QAv/DOMvc7VXl0Pb3kySXFtjpvHt8EUVaEVkpbLIHMpwIoDlj9syq5Vrwqafy
        ///kqChrocpuPv08kUCwEU5iOw3O0qnaVf0ji7FyOvc112GgVoX+1ZKX+HeXXRy1TV9
        ///zHQN/gAH+2yr6tyJAXgDaVfHEYUliQIVAMczp0CNAIWLGttO1pt6AolvZliLAoGA
        ///D8wTO9E1+dL+RN5Vj8XB5ZjxqyREgWzkbg//VA1sHHfTc6jZbfbbYX5yNtrHMJTD
        ///0dno3y6IZFVZMWx08ZJBt5jY1auolPgc0f+5ceh5a7G3h7+aptE6edaZC6yvWQ+Y
        ///E7HJ8Eezid/M7DWFxJj/8/3ZhxWDC+yJ5pFFcG3/WYkDgYUAAoGBAJeA0wGoFEeb
        ///Bw6jSbDkngB9Iu20fRfp9Q1j4eBcNnloYiO7DrblEqK843CV/Y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REQ10DSA {
            get {
                return ResourceManager.GetString("REQ10DSA", resourceCulture);
            }
        }
    }
}
