//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysadminsLV.PKI.Win.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysadminsLV.PKI.Win.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIEpzCCA4+gAwIBAgIKYZ1g8AAAAAAAAjANBgkqhkiG9w0BAQUFADB+MQswCQYD
        ///VQQGEwJMVjEVMBMGA1UEChMMU3lzYWRtaW5zIExWMRwwGgYDVQQLExNJbmZvcm1h
        ///dGlvbiBTeXN0ZW1zMTowOAYDVQQDEzFTeXNhZG1pbnMgTFYgQ2xhc3MgMSBSb290
        ///IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTEwMDQxNDE3NDExNloXDTIwMDQx
        ///NDE2MjU1NVowcjELMAkGA1UEBhMCTFYxFTATBgNVBAoTDFN5c2FkbWlucyBMVjEc
        ///MBoGA1UECxMTSW5mb3JtYXRpb24gU3lzdGVtczEuMCwGA1UEAxMlU3lzYWRtaW5z
        ///IExWIEludGVybmFsIENsYXNzIDEgU3ViQ0EtMTCCASIwDQYJKoZIhvcNAQEBBQAD
        ///ggEPADCCAQoCggEBALhx8OUm5GGYqdGXi4dryi10+lORR8CmQ1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRLIssuer {
            get {
                return ResourceManager.GetString("CRLIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgxrJRX8v8+C134yKM
        ///hPdrd3MOgvVK19c1K4kvRkRUX4ShRANCAAQr5np+dXEGP4GjJToWsLHUzNfpslVi
        ///2eaR1fx0USiJpA4R2vsmuugbncPSAtdYSe0VktSyvbQ4hcGpBkO7Az+A.
        /// </summary>
        internal static string EcDsaPrivKey {
            get {
                return ResourceManager.GetString("EcDsaPrivKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIBcjCCARegAwIBAgIQH+VexXudFJVOiThtWlzSMjAKBggqhkjOPQQDAjAQMQ4w
        ///DAYDVQQDDAVFQ0RTQTAeFw0yMzA5MjAwODU3NDRaFw0yNDA5MjAwOTE3NDRaMBAx
        ///DjAMBgNVBAMMBUVDRFNBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEK+Z6fnVx
        ///Bj+BoyU6FrCx1MzX6bJVYtnmkdX8dFEoiaQOEdr7JrroG53D0gLXWEntFZLUsr20
        ///OIXBqQZDuwM/gKNTMFEwEwYDVR0lBAwwCgYIKwYBBQUHAwIwGwYJKwYBBAGCNxUK
        ///BA4wDDAKBggrBgEFBQcDAjAdBgNVHQ4EFgQUFHWdrrkrnHfzbJ0K0NRrIGqN7ekw
        ///CgYIKoZIzj0EAwIDSQAwRgIhANCHFQWX+xJIFlJFGfzm4xTEoQwalCRM/DzKaatS
        ///691xAiEA5UFGXtNpatrsi/DaiBJKMC+oFyUW3vtaSjwNq3xT1W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EcDsaPubCert {
            get {
                return ResourceManager.GetString("EcDsaPubCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDf87Nzr8yqhPyJ
        ///Kzhgm2NLq56cQhbVyO7YwfFUTtdKSSHIXLYUTTTfeR3Qb4MPH7bedNif32foZZbm
        ///1cAA2KRjMxsSSJA27hinMhGrrbFnHS3autMoeEH7m1mEZWen9Gk6T/txEkGdGkoL
        ///xW6fZcwaPBBN8nF35Xwk1CkVMld7maZQwC2VHzOvZErhCuUZZsBCstfYxPEzfA3/
        ///2e31jLP3uDlCJoKl0KqKBxuFd56Da/MULa5E4P9Qd6TJL/4XZI/bOg+JKg1SOk+Z
        ///5dDJPKR32ir3r5ohLirdus2zfnIWR/ynEaDqv4zkp4zymMC8NLEPhTQ0Puu72wB5
        ///pA/wzntpAgMBAAECggEAbluiF6UO3wyPgWyp6HlKEhTtISU0KX9Nq8TOjnQXhUTK
        ///f/inxRNStbjyZy88Tyyaqb68rPOjOZMuLGwypHgdccDSW00ku9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RsaPrivKey {
            get {
                return ResourceManager.GetString("RsaPrivKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIDATCCAemgAwIBAgIQFsg4A6ZL+7hNz0MMrSYiJzANBgkqhkiG9w0BAQUFADAS
        ///MRAwDgYDVQQDEwdkZXZ1c2VyMCAXDTIzMDgzMTA3NTUzMVoYDzIxMjMwODA3MDc1
        ///NTMxWjASMRAwDgYDVQQDEwdkZXZ1c2VyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
        ///MIIBCgKCAQEA3/Ozc6/MqoT8iSs4YJtjS6uenEIW1cju2MHxVE7XSkkhyFy2FE00
        ///33kd0G+DDx+23nTYn99n6GWW5tXAANikYzMbEkiQNu4YpzIRq62xZx0t2rrTKHhB
        ///+5tZhGVnp/RpOk/7cRJBnRpKC8Vun2XMGjwQTfJxd+V8JNQpFTJXe5mmUMAtlR8z
        ///r2RK4QrlGWbAQrLX2MTxM3wN/9nt9Yyz97g5QiaCpdCqigcbhXeeg2vzFC2uROD/
        ///UHekyS/+F2SP2zoPiSoNUjpPmeXQyTykd9oq96+aIS4q3brNs3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RsaPubCert {
            get {
                return ResourceManager.GetString("RsaPubCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIEMwIBAzCCA/MGCSqGSIb3DQEHAaCCA+QEggPgMIID3DCCAcUGCSqGSIb3DQEHAaCCAbYEggGyMIIBrjCCAaoGCyqGSIb3DQEMCgECoIHEMIHBMBwGCiqGSIb3DQEMAQMwDgQIAl5dRqsSWSkCAgfQBIGghdezTt5SdTa/O7d5A8ZZcFX/Xqx50yNl0B/R5tFXA9BvK81vZhomGHMgS3hCQrNc0WOxNf+sZ70DR+fXxUcQeNeNm/0/9NW4gXnTKZ4Lfu7808FubEmDPy3YrOrSeHJ0l0cYMThe8WZhLlc3X/P4asxbasNAwyeRMp64/dnOowce/Cmb+MD1Oo0tBM3Turtgk59hoRywmFyfYc1cOyVWUzGB0zATBgkqhkiG9w0BCRUxBgQEAQAAADBdBgkqhkiG9w0BCRQxUB5OAGwAcAAtAGUAZAAzAGMAMwBiAGUAMwAtAGIAMwA5ADYALQA0AGMAMwAwAC0AOAAzAGQANQAtADgAZABjADkAOABh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SigningCertCngDsa {
            get {
                return ResourceManager.GetString("SigningCertCngDsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIJ/gIBAzCCCb4GCSqGSIb3DQEHAaCCCa8EggmrMIIJpzCCBgAGCSqGSIb3DQEHAaCCBfEEggXtMIIF6TCCBeUGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAiG05p0nUfcbgICB9AEggTYh3uQDTwP1We33Cexa2lrK+3IoA9j81qg8Y1MhU7jMLsfA3YEQPI3VWuj1EnL6TVwO6TKhbJ+cLNuL8z2S9RVPfv+CVh2CbMD+4g52qB1TKIqTOX2kFXmYtOJoEZkLJuO84FoYsO2TugPigUlq2aaGnBt0EeOmO82t/oZA4urfCoCRi0Gmad3xSHN38FZn8kCtnfZ0py00+Jw8gNSL1D5lTMKCo3LlFYVqQlbKWVYJtqfewJT/o626dd5khEX7u58jknGL+YdlE+xcp/3Uf6f5nWiHOlaUFbkCdUfzS/LWZS4kBcm1DvCxerENhiEgt+RwZo09FZn9Cg1YzzpygAccO2bLsKxeBnS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SigningCertCngRsa {
            get {
                return ResourceManager.GetString("SigningCertCngRsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIKaQIBAzCCCiUGCSqGSIb3DQEHAaCCChYEggoSMIIKDjCCBg8GCSqGSIb3DQEHAaCCBgAEggX8MIIF+DCCBfQGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAi8X8pk9r2ytAICB9AEggTYN4ep46P3mdcBtHTitRLZZKIQETe01+Slw9oy9O+DCzqWpP7b3SL9MgmxlcxtGtnK3mSb72HBXn05YBghSmtFcze+ybN3wbONEPkfa/qZ9nTSjHHLLHOGAw+9XvSM1Zie3GEaubuVs8l4mjYrv74AVikIzD6BU5wj5dQGCvet+ceVy7DgIuwmEFdpo8Bni/yOWafsxzeDFzRE7E8OGLjRPbDclTwHHR2jIgupx5X1jHXQbntuU/PvTlXsPP0fk9SJQifBbb90KGkN9jc3UGO4ptqDdjohbGO5FFKTFuuWMDA/d29GdtLHHxwjzcEupaogxichPT6UFzQDQ4SkCRfcM+yhuglZ4WGl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SigningCertCngRsaPss {
            get {
                return ResourceManager.GetString("SigningCertCngRsaPss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIGQgIBAzCCBgIGCSqGSIb3DQEHAaCCBfMEggXvMIIF6zCCAnwGCSqGSIb3DQEHAaCCAm0EggJpMIICZTCCAmEGCyqGSIb3DQEMCgECoIIBdjCCAXIwHAYKKoZIhvcNAQwBAzAOBAhF6hua8En5HAICB9AEggFQIHvsQIqs2I5q+q8qBCWseGuUmLZGBJiEK25/02k0w7P0qaW22NTIoR0fT9qEr/AN1w8vFdemFbhjCbXiRBFnqqsrG9Do+c1sMmEd/NpbSn/Ifh4DTmrm/QtwLGl0WPqid9Itl17W8U/qnjwZuFWGDHWfkf6NF0qhasQTKwbVzZbEq0Z92OEn4V8/xby9KFEClKUNMQSIHqO5XrJ3IvKYYKHzpWFEbjxyWv3zECBEfICSYfXcJ1SAxfFooZPt65QEMnOUnr5Rzc/xF6NnZr/90yop3PJ+zSZgeXuptLLPXbP4dv73V9IxcCm+KHXP7gg+5v6sdq0piJ9ps1XaQJus+mLaP0BbTcVe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SigningCertLegacyDsa {
            get {
                return ResourceManager.GetString("SigningCertLegacyDsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIKFAIBAzCCCdQGCSqGSIb3DQEHAaCCCcUEggnBMIIJvTCCBg4GCSqGSIb3DQEHAaCCBf8EggX7MIIF9zCCBfMGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAixiFbAFTH4AAICB9AEggTYj4MpipimYSIGv4aVqETvazWMOYxQgGXb4z3DzDq+Lc+dbfSAsJv7JV0ffw4i5mHtI2woJ8qRYrjNUGT4MkqWdfHJY8VOKXt2r3Zmu1uRpJhR+JTm99WCrg90o8zBtyjCGJPkllyMhY46Lzbp4ZDYq485vtBTSsNofIE+R0GJ7LpRtoc7CqxYmt0VT2Udi5BLc6t+EaeAKVMjrHxSKH70L9JvG6Xs50CfRLj7gmTS3iDTyE1oTcjbGIGJLFBsJSAV5nUH1mAtX1lSYem7NuH88txK4cfKMTa3g1AgscTk2+CEQ76UhNXCa+bo8gbREoYl85+cJ9yt9NQyBRWHmgaV93oOgWOxfEC/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SigningCertLegacyRsa {
            get {
                return ResourceManager.GetString("SigningCertLegacyRsa", resourceCulture);
            }
        }
    }
}
